[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
packages = [
  { include = "rapidpro_flow_tools",
  { include = "rapidpro_flow_tools.*" }
]

[project]
name = "rapidpro_flow_tools"
version = "0.4.0"
authors = [
  { name="Ed Moss", email="ed.moss@eemengineering.com" },
]
description = "Toolkit for using spreadsheets to create and modify RapidPro flows"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/IDEMSInternational/rapidpro-flow-toolkit"
"Bug Tracker" = "https://github.com/IDEMSInternational/rapidpro-flow-toolkit/issues"